### ISSUE TITLE
osx build

### ISSUE THREAD

**Issue by tablatronix** [oceanofthelost/InteractiveBOM#14]
I am trying to build on osx, anyone know what this means?
No idea where this path is coming from

```php
Error: Cannot find module '/Users/shawn/.srcpcbfont.js' from '/Users/shawn'
    at /Users/shawn/.npm/_npx/35884/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/shawn/.npm/_npx/35884/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/shawn/.npm/_npx/35884/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/shawn/.npm/_npx/35884/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:159:21)
```

**Comment by tablatronix** [comment]
Ill try absolute paths and see what happens, no idea why its picking up that path

**Comment by tablatronix** [comment]
im dumb, fixed it , somehow I was in the wrong dir, geez more coffee
